"""messages tablosuna message_id_header eklendi

Revision ID: c6f2e5a0b6af
Revises: 467b43450125
Create Date: 2026-08-16 20:43:29.383863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6f2e5a0b6af'
down_revision: Union[str, Sequence[str], None] = '467b43450125'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('message_id_header', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'messages', ['message_id_header'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='unique')
    op.drop_column('messages', 'message_id_header')
    # ### end Alembic commands ###
